### ISSUE TITLE
What does "baseline" mean?

### ISSUE THREAD

**Issue by kevinanewman** [USEPA/EPA_OMEGA_Model#5]
Currently, the word "baseline" may have many meanings depending on context, we should come up with context-specific words and meanings for those things.

For example:

- "Baseline Fleet"
     -> pre-compliance fleet?
     -> initial fleet?
     -> starting vehicle market?

Task: 
    Figure out what all the current uses of "baseline" are and then arrive at consensus for new terms then document in the OMEGA Glossary

**Comment by epaneam** [comment]
The baseline line fleet is the fleet of vehicles that exist in the baseline year.  The Future fleet volumes are the projected volumes of those vehicle in future years.

**Comment by pdekraker-epa** [comment]
In hope of matching the regulatory analysis terminology, I think baseline should be reserved for projections which exclude the regulation under consideration. I like initial fleet, but depending on how the data structures are organized initial vehicle market could be more accurate.

**Comment by kbolon** [comment]
Coming at this from the other way, there are a couple of concepts that need consistent terminology:

**A scenario that excludes the regulations under consideration**: Here, the plain-language terms could include "baseline" and "reference". Recently, we've been using "reference", but I think that either can work. We just need to then prohibit the use of these terms to mean something else (which is what causes the confusion with our current use of "baseline" to mean the current fleet of vehicles).  "Control" is another common-language term which is normally used in experimental science to mean the sample that doesn't receive the treatment being studied. We've been using that term to mean the exact opposite. I don't know how commonly "control" is being used across the government to mean the regulations under consideration, but unless the term is being used officially by OMB, I think we should avoid it.

**A scenario that consists of the regulations under consideration**: Again, we have used "control" in the past, but I think we need to replace that with another term. The CAFE model uses the term "Action Alternative", which I think is precise and unambiguous. It also offers another choice for the topic above: "No Action Alternative", along with "baseline" and "reference.

**The historical fleet of vehicles and their attributes**: We've been using the term "baseline", which is why this thread was started.  Why don't we call it the "historical fleet"? That would be clear, and the use of "fleet" is flexible enough to include both the actual volumes, and vehicle characteristics, and allows us to accommodate more than one model year, which may be important for tracking the most recent prior redesign year(s), or the on-road fleet characteristics we might need for a scrappage model.
